name: ${{APP_NAME:-default}}
options:
  services:
    - name: sync-consumer
      options:
        value: wp-queue-sync # Queue
        url: ${{RABBITMQ_URL:-amqp://guest:guest@host.docker.internal:5672}}
    - name: sync-producer
      options:
        value: wp-queue-sync # Queue
        url: ${{RABBITMQ_URL:-amqp://guest:guest@host.docker.internal:5672}}
    - name: database-connection
      options:
        value: followed # Database name for operation
        url: ${{DATA_BASE_URL:-database://root:rootpassword@host.docker.internal:27017/followed}}

  dev:
    port: ${{APP_PORT:-3000}}
