services:
  http-app:
    restart: always
    build:
      context: .
      target: dev
    command: "npm run http-app:dev"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - ./src:/app/src
      - ./bin:/app/bin
      - /app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - .env.local
  cli-app-producer:
    restart: always
    build:
      context: .
      target: dev
    command: "npm run cli-app:dev -- -- producer"
    volumes:
      - ./:/app
      - ./src:/app/src
      - ./bin:/app/bin
      - /app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - .env.local
  cli-app-consumer:
    restart: always
    build:
      context: .
      target: dev
    command: "npm run cli-app:dev -- -- consumer"
    volumes:
      - ./:/app
      - ./src:/app/src
      - ./bin:/app/bin
      - /app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - .env.local
